name: List Repo

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main

jobs:
  list-repo:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Check current path
      run: |
        pwd

    - name: List Repo
      run: |
        echo "This is a sample step to just list files in the repository"
        find . -maxdepth 2
