name: Sample Build Test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main

jobs:
  sample-build-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        echo "This step should build application"

    - name: Test application
      run: |
        echo "This step should test application"

    - name: Build & push Docker Image
      run: |
        echo "This step should build & push Docker image"
        echo "Accessing Github Secret: "
        echo ${{ secrets.SECRET_VAR }}
